wd: "/hps/software/users/flicek/rimoldi/Scripts/3DGenomeEvo/SM_PCE/"
rd1: "/nfs/research/flicek/user/rimoldi/Projects/PCHIC/Analyses/Processing/"
rawdata: "/nfs/research/flicek/user/rimoldi/DATA/PCHIC/"

genome_path: "/nfs/research/flicek/user/rimoldi/Genomes/98/"
bowtie2: "/hps/software/users/flicek/rimoldi/anaconda3/envs/PCHIC/bin/bowtie2"
digest_path: "/nfs/research/flicek/user/rimoldi/Genomes/98/Digest/"
probesDir: "/nfs/research/flicek/user/rimoldi/Projects/PCHIC/Design/Probes/Final"
#CHRSIZES:
#- "/path/to/genome/chrom.sizes.tsv"
#ASMBLY:
#- "hg38"